# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest2():
  def setup_method(self):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()
  
  def test_test2(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1936, 1096)
    # Assert que el header "Shop by Category:" sea visible
    category = self.driver.find_element(By.CLASS_NAME, "displayCategory").text
    assert "Shop by Category:" in category
    self.driver.find_element(By.ID, "itemImage").click()
    self.driver.find_element(By.ID, "logo").click()
    assert "Shop by Category:" in category
    self.driver.find_element(By.CSS_SELECTOR, "table:nth-child(2) td:nth-child(2) #itemImage").click()
    self.driver.find_element(By.ID, "logo").click()
    assert "Shop by Category:" in category
    self.driver.find_element(By.CSS_SELECTOR, "table:nth-child(2) td:nth-child(3) #itemImage").click()
    self.driver.find_element(By.ID, "logo").click()
    assert "Shop by Category:" in category
    self.driver.find_element(By.LINK_TEXT, "Computers and Accessories").click()
    self.driver.find_element(By.ID, "logo").click()
    assert "Shop by Category:" in category
    # Mostar algun mensaje en consola de exito
    print("Se completo exitosamente el test")

#-----------Main-----------------#
test = TestTest2()
test.setup_method()
test.test_test2()
test.teardown_method()