# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest1():
  def setup_method(self):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()
  
  def test_test1(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(965, 775)
    # Assert que la barra de busqueda sea visible
    logo = self.driver.find_element(By.ID, "searchBox").is_displayed()
    assert logo == True
    self.driver.find_element(By.ID, "searchBox").click()
    self.driver.find_element(By.ID, "searchBox").send_keys("dress")
    self.driver.find_element(By.ID, "searchButton").click()
    # Mostar algun mensaje en consola de exito
    print("Se completo exitosamente el test")

#-----------Main-----------------#
test = TestTest1()
test.setup_method()
test.test_test1()
test.teardown_method()