# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest3():
  def setup_method(self):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()
  
  def test_test3(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1936, 1096)
    # Assert que ningun perfil este logueado
    sing_in = self.driver.find_element(By.LINK_TEXT, "Sign In").is_displayed()
    assert sing_in == True
    self.driver.find_element(By.LINK_TEXT, "Sign In").click()
    self.driver.find_element(By.NAME, "email").send_keys("pepe@gmail.com")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("1234")
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(3) > input").click()
    # Assert user name sea pepe y este visible
    user_name = self.driver.find_element(By.CLASS_NAME, "dropbtn").text
    assert "pepe" in user_name
    # Mostar algun mensaje en consola de exito
    print("Se completo exitosamente el test")

#-----------Main-----------------#
test = TestTest3()
test.setup_method()
test.test_test3()
test.teardown_method()
